In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
torch.cuda.init() #Not needed for python, just c++

In [4]:
torch.cuda.current_device()


0

In [5]:
torch.cuda.device_count()

1

In [6]:
torch.cuda.memory_allocated() # Returns memory of tensors

0

In [9]:
torch.cuda.memory_reserved() #Cached memory

0

In [11]:
c = torch.device('cuda') # Reference to cuda device
c

device(type='cuda')

In [15]:
x = torch.tensor([2,3,5], device = c) # Device specific tensors
z =torch.tensor([2,323,1,6])


In [13]:
x

tensor([2, 3, 5], device='cuda:0')

In [17]:
y = z.cuda() # Explicit copy to other device
print(y)
print(z)

tensor([  2, 323,   1,   6], device='cuda:0')
tensor([  2, 323,   1,   6])


In [30]:
with torch.cuda.device(0):
    a = torch.tensor([2,3,5,2,1,5], device = 'cpu')
    b = torch.tensor([2,3,5,2,1,5], device = 'cuda')

In [31]:
a.device
b.device

device(type='cuda', index=0)

In [32]:
torch.cuda.memory_allocated()

2560

In [33]:
torch.cuda.memory_reserved()

2097152

In [36]:
torch.cuda.empty_cache()

In [37]:
torch.cuda.memory_reserved()

2097152

In [38]:
torch.cuda.memory_allocated()

2560