# Computing Gradients with AutoGrad

Automatic diferentiation: Forward and Backward Pass based on Taylor's Series Expansion. Reverse_mode since you only use one pass for every parameter.

In [69]:
import torch
from torch.autograd import Variable

In [7]:
t = torch.Tensor ([[1,2,3],[4,5,6]])
t2 = torch.Tensor ([[17,27,73],[48,59,69]])
t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [32]:
t.requires_grad
t.requires_grad_()# Enable requires grad

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [12]:
t2.requires_grad

False

In [14]:
print(t.grad) # Check for gradients to calculate

None


In [15]:
print(t.grad_fn)

None


In [17]:
out_t = t * t2

In [18]:
out_t.requires_grad

True

In [20]:
out_t.grad_fn #references last function that created tensor. IT is a modular way of creating backward passes with pointers

In [22]:
t.shape

torch.Size([2, 3])

In [49]:
with torch.no_grad(): #new tensors have require grad off even if parent has it on
    n_t = t *3 
    print(n_t.requires_grad)
pass

False


In [50]:
def cal(t):
    return t *2


In [56]:
@torch.no_grad()
def cal_no_grad(t):
    return t*2

In [57]:
n_t2 = cal(t)
n_t2

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]], grad_fn=<MulBackward0>)

In [58]:
n_t2 = cal_no_grad(t)
print(n_t2.requires_grad)

False


In [59]:
with torch.enable_grad(): #Enables
    pass

In [62]:
t3 = torch.Tensor([[12,12,53],
                   [44,35,36]], requires_grad = True) # Probably version error

TypeError: new() received an invalid combination of arguments - got (list, requires_grad=bool), but expected one of:
 * (*, torch.device device)
      didn't match because some of the keywords were incorrect: requires_grad
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, *, torch.device device)
 * (object data, *, torch.device device)


In [66]:
f_t = (t * t2).mean()
f_t.backward() #Calculates grads

In [68]:
d_t = t.detach() # outside of graph (Network)

Simple Neural Network
