In [2]:
import torch
print(torch.__version__)

1.11.0+cpu


In [4]:
torch.set_default_dtype(torch.float64)

In [5]:
torch.get_default_dtype()

torch.float64

In [7]:
tensor_arr = torch.Tensor([[1,2,3],[4,5,6]]) # basic tensor of torch
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [8]:
torch.numel(tensor_arr)

6

In [10]:
tensor_uninitialized = torch.Tensor(2,2) # uninit memory allocation
tensor_uninitialized

tensor([[1.1034e-312,  2.9297e-33],
        [ 4.4684e-90,  4.6615e-33]])

In [14]:
""" Type:
    torch.half
    torch.int16
    torch.int32
    torch.float64
"""
zeros= torch.zeros_like(tensor_arr)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [19]:
i = torch.tensor([[0,1,1],[2,2,0]])
v = torch.tensor([3,4,5],dtype = torch.float32)

In [20]:
sparse_tensor = torch.sparse_coo_tensor(i,v,[2,5]) #Sparse data(low space)
sparse_tensor

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)

In [22]:
x = torch.linspace(start= 0.1, end = 10, steps = 15 )
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [24]:
torch.cat((x,x), 0)

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000,  0.1000,
         0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,  5.7571,
         6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

Tensors are like numpy arrays build specifically for pytorch management

In [29]:
y= x.view([3,5]) #reshape
y

tensor([[ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286],
        [ 3.6357,  4.3429,  5.0500,  5.7571,  6.4643],
        [ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]])

In [28]:
y.size()

torch.Size([3, 5])

In [30]:
z =torch.unsqueeze(y,2)
z

tensor([[[ 0.1000],
         [ 0.8071],
         [ 1.5143],
         [ 2.2214],
         [ 2.9286]],

        [[ 3.6357],
         [ 4.3429],
         [ 5.0500],
         [ 5.7571],
         [ 6.4643]],

        [[ 7.1714],
         [ 7.8786],
         [ 8.5857],
         [ 9.2929],
         [10.0000]]])

In [32]:
z.size()

torch.Size([3, 5, 1])

In [34]:
torch.transpose(z, 0, 1).size()

torch.Size([5, 3, 1])

In [40]:
sorted_tensor, sorted_indices = torch.sort(y,axis = 0)
sorted_tensor
sorted_indices

tensor([[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2]])

In [42]:
clamp = torch.clamp(y , min= 2, max = 8)
clamp

tensor([[2.0000, 2.0000, 2.0000, 2.2214, 2.9286],
        [3.6357, 4.3429, 5.0500, 5.7571, 6.4643],
        [7.1714, 7.8786, 8.0000, 8.0000, 8.0000]])