In [1]:
import numpy as np
import torch

In [4]:
t = torch.Tensor([2,4,5]) 
n = t.numpy()

In [8]:
print(type(n))
print(type(t)) 

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [10]:
#They share the memory
n[1]= 0
print(t)

tensor([2., 0., 5.])


In [12]:
t2 = torch.from_numpy(n)
t2

tensor([2., 0., 5.])

In [13]:
t2[2] = 1 
t

tensor([2., 0., 1.])

In [14]:
t3 = torch.as_tensor(n)

In [19]:
#Copy of data 
t4 = torch.tensor(n)
t4[0]= 25
print(n)
print(t4.numpy())

[2. 0. 1.]
[25.  0.  1.]


In [28]:
help(torch.cuda.is_available)

Help on function is_available in module torch.cuda:

is_available() -> bool
    Returns a bool indicating if CUDA is currently available.

